namespace epms.Entities.Models
{


    // ------------------------------------------------------------------------------------------------
    // This code was generated by EntityFramework Reverse POCO Generator (http://www.reversepoco.com/).
    // Created by Simon Hughes (https://about.me/simon.hughes).
    //
    // Do not make changes directly to this file - edit the template instead.
    //
    // The following connection settings were used to generate this file:
    //     Configuration file:     "F:\asp.net\EPMS\epms.DataTest\App.config"
    //     Connection String Name: "MyDbContext"
    //     Connection String:      "Server= 127.0.0.1;Database=TestDB;User Id=sa;password=**zapped**;;"
    // ------------------------------------------------------------------------------------------------
    // Database Edition       : Data Center Edition
    // Database Engine Edition: Enterprise

    // <auto-generated>
    // ReSharper disable ConvertPropertyToExpressionBody
    // ReSharper disable DoNotCallOverridableMethodsInConstructor
    // ReSharper disable EmptyNamespace
    // ReSharper disable InconsistentNaming
    // ReSharper disable PartialMethodWithSinglePart
    // ReSharper disable PartialTypeWithSinglePart
    // ReSharper disable RedundantNameQualifier
    // ReSharper disable RedundantOverridenMember
    // ReSharper disable UseNameofExpression
    // TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


    namespace epms.Data.Mapping
    {
        #region POCO Configuration

        // AccountGroup
        [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.34.1.0")]
        public class AccountGroupConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<AccountGroup>
        {
            public AccountGroupConfiguration()
                : this("dbo")
            {
            }

            public AccountGroupConfiguration(string schema)
            {
                ToTable("AccountGroup", schema);
                HasKey(x => x.Id);

                Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
                Property(x => x.GroupCode).HasColumnName(@"GroupCode").HasColumnType("nvarchar").IsOptional().HasMaxLength(50);
                Property(x => x.GroupName).HasColumnName(@"GroupName").HasColumnType("nvarchar").IsOptional().HasMaxLength(200);
                Property(x => x.CompanyId).HasColumnName(@"CompanyId").HasColumnType("int").IsOptional();
                Property(x => x.IsActive).HasColumnName(@"IsActive").HasColumnType("bit").IsOptional();

                // Foreign keys
                HasOptional(a => a.Company).WithMany(b => b.AccountGroups).HasForeignKey(c => c.CompanyId).WillCascadeOnDelete(false); // FK_AccountGroup_Company
            }
        }

        #endregion

    }
    // </auto-generated>


}
